import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
  Legend,
} from "recharts";
import { Loader2 } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { EmptyState } from "@/components/churn/EmptyState";
import { ChartCard } from "@/components/churn/ChartCard";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import type { MetricsFile, ModelMetrics } from "@/lib/churn/types";

export const Route = createFileRoute("/performance")({
  head: () => ({
    meta: [
      { title: "Model Performance — ChurnScope" },
      {
        name: "description",
        content:
          "Real evaluation results for the churn models: accuracy, precision, recall, F1, ROC-AUC, confusion matrix and ROC curve.",
      },
      { property: "og:title", content: "Model Performance — ChurnScope" },
      {
        property: "og:description",
        content: "Logistic Regression versus Random Forest evaluation results.",
      },
      { property: "og:url", content: "/performance" },
    ],
    links: [{ rel: "canonical", href: "/performance" }],
  }),
  component: Performance,
});

const METRIC_KEYS = ["accuracy", "precision", "recall", "f1", "roc_auc"] as const;
const METRIC_LABELS: Record<(typeof METRIC_KEYS)[number], string> = {
  accuracy: "Accuracy",
  precision: "Precision",
  recall: "Recall",
  f1: "F1 score",
  roc_auc: "ROC-AUC",
};

function Performance() {
  const [metrics, setMetrics] = useState<MetricsFile | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let active = true;
    fetch("/model/model_metrics.json", { cache: "no-store" })
      .then((r) => (r.ok ? r.json() : null))
      .then((json: MetricsFile | null) => {
        if (!active) return;
        setMetrics(json && json.models ? json : null);
        setLoading(false);
      })
      .catch(() => {
        if (!active) return;
        setMetrics(null);
        setLoading(false);
      });
    return () => {
      active = false;
    };
  }, []);

  const models = metrics ? Object.entries(metrics.models) : [];

  return (
    <div className="mx-auto max-w-7xl space-y-6 px-4 py-10 sm:px-6">
      <header>
        <h1 className="text-2xl font-semibold tracking-tight text-foreground">Model Performance</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          These results are read from <code>public/model/model_metrics.json</code>, generated by the
          Python training script. Nothing on this page is hard-coded.
        </p>
      </header>

      <Alert>
        <AlertTitle>Why recall matters most here</AlertTitle>
        <AlertDescription>
          Recall is the share of customers who really did churn that the model managed to flag. If
          the business goal is to catch as many at-risk customers as possible, a missed churner is
          far more costly than a retention offer sent to someone who would have stayed. A model with
          high precision but low recall looks tidy on paper while quietly letting most leavers slip
          away.
        </AlertDescription>
      </Alert>

      {loading ? (
        <p className="flex items-center gap-2 text-sm text-muted-foreground">
          <Loader2 className="size-4 animate-spin" aria-hidden="true" /> Looking for exported
          results…
        </p>
      ) : !metrics ? (
        <EmptyState
          title="Run the model pipeline to generate results."
          description="Execute data-science/train_model.py and copy outputs/model_metrics.json into public/model/ to display real evaluation results here."
        />
      ) : (
        <>
          <div className="grid gap-6 lg:grid-cols-2">
            {models.map(([name, m]) => (
              <ModelSection key={name} name={name} metrics={m} />
            ))}
          </div>

          <ChartCard
            title="Model comparison"
            description="Side-by-side comparison of the evaluated models."
          >
            <ResponsiveContainer width="100%" height="100%">
              <BarChart
                data={METRIC_KEYS.map((k) => {
                  const row: Record<string, string | number> = { metric: METRIC_LABELS[k] };
                  for (const [name, m] of models) row[name] = Number((m[k] ?? 0).toFixed(4));
                  return row;
                })}
                margin={{ top: 8, right: 8, bottom: 4, left: -16 }}
              >
                <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" />
                <XAxis dataKey="metric" tick={{ fontSize: 12 }} />
                <YAxis domain={[0, 1]} tick={{ fontSize: 12 }} />
                <Tooltip />
                <Legend />
                {models.map(([name], i) => (
                  <Bar
                    key={name}
                    dataKey={name}
                    fill={`var(--color-chart-${(i % 5) + 1})`}
                    radius={[4, 4, 0, 0]}
                  />
                ))}
              </BarChart>
            </ResponsiveContainer>
          </ChartCard>
        </>
      )}
    </div>
  );
}

function ModelSection({ name, metrics }: { name: string; metrics: ModelMetrics }) {
  const cm = metrics.confusion_matrix ?? [];
  const roc = metrics.roc_curve;
  const rocData =
    roc?.fpr?.map((f, i) => ({
      fpr: Number(f.toFixed(4)),
      tpr: Number((roc.tpr[i] ?? 0).toFixed(4)),
    })) ?? [];

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-base">{name}</CardTitle>
        <CardDescription>Held-out test set results exported by the pipeline.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <dl className="grid grid-cols-2 gap-3 sm:grid-cols-5">
          {METRIC_KEYS.map((k) => (
            <div key={k} className="rounded-lg border border-border bg-secondary/50 p-3">
              <dt className="text-xs text-muted-foreground">{METRIC_LABELS[k]}</dt>
              <dd className="mt-1 text-lg font-semibold text-foreground">
                {typeof metrics[k] === "number" ? metrics[k].toFixed(3) : "—"}
              </dd>
            </div>
          ))}
        </dl>

        {cm.length === 2 ? (
          <div>
            <h3 className="text-sm font-semibold text-foreground">Confusion matrix</h3>
            <table className="mt-2 w-full border-collapse text-sm">
              <caption className="sr-only">Confusion matrix for {name}</caption>
              <thead>
                <tr>
                  <th scope="col" className="p-2 text-left text-xs text-muted-foreground"></th>
                  <th scope="col" className="p-2 text-xs text-muted-foreground">
                    Predicted: No churn
                  </th>
                  <th scope="col" className="p-2 text-xs text-muted-foreground">
                    Predicted: Churn
                  </th>
                </tr>
              </thead>
              <tbody>
                {["Actual: No churn", "Actual: Churn"].map((label, r) => (
                  <tr key={label}>
                    <th scope="row" className="p-2 text-left text-xs text-muted-foreground">
                      {label}
                    </th>
                    {cm[r].map((v, c) => (
                      <td
                        key={c}
                        className="rounded-md border border-border bg-card p-2 text-center font-medium text-foreground"
                      >
                        {v.toLocaleString()}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : null}

        {rocData.length ? (
          <div className="h-56">
            <h3 className="mb-2 text-sm font-semibold text-foreground">ROC curve</h3>
            <ResponsiveContainer width="100%" height="85%">
              <LineChart data={rocData} margin={{ top: 4, right: 8, bottom: 4, left: -20 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" />
                <XAxis
                  dataKey="fpr"
                  type="number"
                  domain={[0, 1]}
                  tick={{ fontSize: 11 }}
                />
                <YAxis domain={[0, 1]} tick={{ fontSize: 11 }} />
                <Tooltip />
                <Line
                  type="monotone"
                  dataKey="tpr"
                  stroke="var(--color-chart-1)"
                  dot={false}
                  strokeWidth={2}
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        ) : null}

        {metrics.feature_importance?.length ? (
          <div className="h-64">
            <h3 className="mb-2 text-sm font-semibold text-foreground">Feature importance</h3>
            <ResponsiveContainer width="100%" height="88%">
              <BarChart
                layout="vertical"
                data={metrics.feature_importance.slice(0, 10)}
                margin={{ top: 4, right: 16, bottom: 4, left: 8 }}
              >
                <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" />
                <XAxis type="number" tick={{ fontSize: 11 }} />
                <YAxis type="category" dataKey="feature" width={140} tick={{ fontSize: 11 }} />
                <Tooltip />
                <Bar dataKey="importance" fill="var(--color-chart-2)" radius={[0, 4, 4, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        ) : null}
      </CardContent>
    </Card>
  );
}
